package com.masterwok.opensubtitlesandroid.models

import com.github.kittinunf.fuel.core.ResponseDeserializable
import com.google.gson.Gson

data class OpenSubtitleItem(
        val MatchedBy: String,
        val IDSubMovieFile: String,
        val MovieHash: String,
        val MovieByteSize: String,
        val MovieTimeMS: String,
        val IDSubtitleFile: String,
        val SubFileName: String,
        val SubActualCD: String,
        val SubSize: String,
        val SubHash: String,
        val SubLastTS: String,
        val SubTSGroup: String,
        val InfoReleaseGroup: String,
        val InfoFormat: String,
        val InfoOther: String,
        val IDSubtitle: String,
        val UserID: String,
        val SubLanguageID: String,
        val SubFormat: String,
        val SubSumCD: String,
        val SubAuthorComment: String,
        val SubAddDate: String,
        val SubBad: String,
        val SubRating: String,
        val SubSumVotes: String,
        val SubDownloadsCnt: String,
        val MovieReleaseName: String,
        val MovieFPS: String,
        val IDMovie: String,
        val IDMovieImdb: String,
        val MovieName: String,
        val MovieNameEng: String,
        val MovieYear: String,
        val MovieImdbRating: String,
        val SubFeatured: String,
        val UserNickName: String,
        val SubTranslator: String,
        val ISO639: String,
        val LanguageName: String,
        val SubComments: String,
        val SubHearingImpaired: String,
        val UserRank: String,
        val SeriesSeason: String,
        val SeriesEpisode: String,
        val MovieKind: String,
        val SubHD: String,
        val SeriesIMDBParent: String,
        val SubEncoding: String,
        val SubAutoTranslation: String,
        val SubForeignPartsOnly: String,
        val SubFromTrusted: String,
        val QueryParameters: QueryParameters,
        val SubTSGroupHash: String,
        val SubDownloadLink: String,
        val ZipDownloadLink: String,
        val SubtitlesLink: String,
        val QueryNumber: String,
        val Score: Double
) {
    companion object Deserializer : ResponseDeserializable<Array<OpenSubtitleItem>> {
        override fun deserialize(content: String): Array<OpenSubtitleItem>? = Gson().fromJson(content, Array<OpenSubtitleItem>::class.java)
    }
}